# Generated by Django 3.2.20 on 2023-07-30 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_tripbooking_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
