# Generated by Django 3.2.20 on 2023-07-30 09:38

import ExamProject.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_tripbooking_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='guests',
            field=models.PositiveIntegerField(validators=[ExamProject.common.validators.guests_validator]),
        ),
    ]
