# Generated by Django 3.2.20 on 2023-07-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_addbookingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddBookingModel',
        ),
    ]
