# Generated by Django 3.2.20 on 2023-07-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageModel',
        ),
    ]
