# Generated by Django 3.2.20 on 2023-07-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_addbookingmodel_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbookingmodel',
            name='image',
            field=models.ImageField(upload_to='user_pictures'),
        ),
    ]
