# Generated by Django 3.2.20 on 2023-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230730_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='repeatPassword',
            field=models.CharField(max_length=30),
        ),
    ]
