# Generated by Django 3.2.20 on 2023-07-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_loginmodel_repeatpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
