# Generated by Django 3.2.20 on 2023-07-30 18:53

import ExamProject.main.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230730_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'Username must be at least 3 characters')])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8, 'Password should contain at least 8 symbols'), ExamProject.main.validators.atleast_one_digit])),
                ('repeatPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='repeatPassword',
        ),
    ]
