# Generated by Django 3.2.20 on 2023-08-05 10:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_registrationmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username already exists'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username must be at least 3 characters')]),
        ),
    ]
