# Generated by Django 3.2.20 on 2023-08-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230805_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationModel',
        ),
    ]
