# Generated by Django 3.2.20 on 2023-08-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_registrationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingimagemodel',
            old_name='image',
            new_name='images',
        ),
    ]
