# Generated by Django 3.2.20 on 2023-08-11 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_image_bookingimagemodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbookingmodel',
            name='images',
            field=models.FileField(default=django.utils.timezone.now, upload_to='user_pictures'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingImageModel',
        ),
    ]
